<a href="https://colab.research.google.com/github/tonHS/GDP-and-related-intl-stats/blob/main/Scratch_test_GDP_etc_dashboard_v1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [74]:
# Install Dependencies and Packages
!pip install stats-can openpyxl

import pandas as pd
import requests
import zipfile
from io import BytesIO
from pathlib import Path
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime

Requirement already satisfied: stats-can in /usr/local/lib/python3.12/dist-packages (3.1.0)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from stats-can) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from stats-can) (4.67.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from stats-can) (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from stats-can) (2.0.2)
Requirement already satisfied: pydantic>=2.9.2 in /usr/local/lib/python3.12/dist-packages (from stats-can) (2.12.3)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.9.2->stats-can) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.9.2->stats-can) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.9.2->stats-can) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.9.2->stats-can) (0.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->stats-can) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->stats-can) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->stats-can) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->stats-can) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->stats-can) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->stats-can) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->stats-can) (2026.2.25)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->stats-can) (1.17.0)

In [75]:
##############################
# Testing IMF API by fetching US and China GDP data
##############################

response = requests.get("https://www.imf.org/external/datamapper/api/v1/NGDP_RPCH/USA/CHN")

df_response_json = response.json()

print(df_response_json)

{'values': {'NGDP_RPCH': {'CHN': {'1980': 7.9, '1981': 5.1, '1982': 9, '1983': 10.8, '1984': 15.2, '1985': 13.5, '1986': 8.9, '1987': 11.7, '1988': 11.2, '1989': 4.2, '1990': 3.9, '1991': 10.2, '1992': 14.3, '1993': 13.9, '1994': 13.1, '1995': 11, '1996': 10, '1997': 9.3, '1998': 7.9, '1999': 7.8, '2000': 8.6, '2001': 8.3, '2002': 9.2, '2003': 10.1, '2004': 10.1, '2005': 11.4, '2006': 12.7, '2007': 14.2, '2008': 9.6, '2009': 9.4, '2010': 10.6, '2011': 9.5, '2012': 7.8, '2013': 7.8, '2014': 7.5, '2015': 7, '2016': 6.8, '2017': 6.9, '2018': 6.8, '2019': 6.1, '2020': 2.3, '2021': 8.6, '2022': 3.1, '2023': 5.4, '2024': 5, '2025': 4.8, '2026': 4.2, '2027': 4.2, '2028': 4, '2029': 3.7, '2030': 3.4}, 'USA': {'1980': -0.3, '1981': 2.5, '1982': -1.8, '1983': 4.6, '1984': 7.2, '1985': 4.2, '1986': 3.5, '1987': 3.5, '1988': 4.2, '1989': 3.7, '1990': 1.9, '1991': -0.1, '1992': 3.5, '1993': 2.8, '1994': 4, '1995': 2.7, '1996': 3.8, '1997': 4.4, '1998': 4.5, '1999': 4.8, '2000': 4.1, '2001': 1, '2002': 1.7, '2003': 2.8, '2004': 3.8, '2005': 3.5, '2006': 2.8, '2007': 2, '2008': 0.1, '2009': -2.6, '2010': 2.7, '2011': 1.6, '2012': 2.3, '2013': 2.1, '2014': 2.5, '2015': 2.9, '2016': 1.8, '2017': 2.5, '2018': 3, '2019': 2.6, '2020': -2.1, '2021': 6.2, '2022': 2.5, '2023': 2.9, '2024': 2.8, '2025': 2, '2026': 2.1, '2027': 2.1, '2028': 2.1, '2029': 1.9, '2030': 1.8}}}, 'api': {'version': '1', 'output-method': 'json'}}

In [76]:
############################
# Convert JSON into Data Frame
############################

#Extract nested data from the JSON, ensuring years are the index and countries are columns.


gdp_growth_data = df_response_json['values']['NGDP_RPCH']
df_gdp_growth = pd.DataFrame(gdp_growth_data)
df_gdp_growth.head()

       CHN  USA
1980   7.9 -0.3
1981   5.1  2.5
1982   9.0 -1.8
1983  10.8  4.6
1984  15.2  7.2

In [77]:
##############################
# Using IMF API to fetch GDP data for all countries
##############################

response2 = requests.get("https://www.imf.org/external/datamapper/api/v1/NGDPD")

df2_response_json = response2.json()

print(df2_response_json)

{'values': {'NGDPD': {'SDN': {'1980': 9.095, '1981': 6.53, '1982': 4.748, '1983': 6.485, '1984': 7.992, '1985': 5.547, '1986': 7.4, '1987': 11.964, '1988': 9.551, '1989': 16.853, '1990': 2.245, '1991': 2.528, '1992': 3.1, '1993': 5.246, '1994': 5.961, '1995': 6.694, '1996': 8.377, '1997': 10.241, '1998': 10.924, '1999': 10.714, '2000': 13.134, '2001': 15.716, '2002': 18.137, '2003': 21.355, '2004': 26.646, '2005': 35.183, '2006': 45.264, '2007': 59.44, '2008': 64.833, '2009': 54.812, '2010': 65.716, '2011': 66.448, '2012': 48.948, '2013': 52.892, '2014': 60.726, '2015': 64.534, '2016': 64.888, '2017': 48.906, '2018': 33.59, '2019': 31.484, '2020': 35.237, '2021': 35.141, '2022': 33.5, '2023': 36.983, '2024': 29.184, '2025': 35.897, '2026': 39.474, '2027': 46.09, '2028': 50.54, '2029': 52.73, '2030': 55.57}, 'AFG': {'2002': 4.367, '2003': 4.553, '2004': 5.146, '2005': 6.167, '2006': 6.925, '2007': 8.556, '2008': 10.297, '2009': 12.066, '2010': 15.325, '2011': 17.89, '2012': 20.293, '2013': 20.17, '2014': 20.616, '2015': 20.057, '2016': 18.02, '2017': 18.883, '2018': 18.336, '2019': 18.876, '2020': 20.136, '2021': 14.278, '2022': 14.501, '2023': 17.248, '2024': 18.08}, 'ALB': {'1980': 1.946, '1981': 2.229, '1982': 2.296, '1983': 2.319, '1984': 2.29, '1985': 2.339, '1986': 2.587, '1987': 2.566, '1988': 2.53, '1989': 2.779, '1990': 2.221, '1991': 1.333, '1992': 0.843, '1993': 1.461, '1994': 2.361, '1995': 2.882, '1996': 3.2, '1997': 2.225, '1998': 2.555, '1999': 3.226, '2000': 3.488, '2001': 3.927, '2002': 4.356, '2003': 5.561, '2004': 7.177, '2005': 8.052, '2006': 8.896, '2007': 10.677, '2008': 12.881, '2009': 12.044, '2010': 11.937, '2011': 12.899, '2012': 12.324, '2013': 12.784, '2014': 13.246, '2015': 11.389, '2016': 11.862, '2017': 13.053, '2018': 15.38, '2019': 15.582, '2020': 15.271, '2021': 17.985, '2022': 19.189, '2023': 23.633, '2024': 27.084, '2025': 29.939, '2026': 32.411, '2027': 34.208, '2028': 36.358, '2029': 38.657, '2030': 41.115}, 'DZA': {'1980': 45.957, '1981': 48.156, '1982': 48.599, '1983': 51.582, '1984': 55.906, '1985': 66.346, '1986': 66.783, '1987': 68.698, '1988': 56.07, '1989': 57.041, '1990': 67.171, '1991': 50.65, '1992': 53.414, '1993': 55.309, '1994': 46.044, '1995': 45.654, '1996': 50.945, '1997': 52.287, '1998': 52.297, '1999': 53.011, '2000': 59.418, '2001': 59.413, '2002': 61.516, '2003': 73.482, '2004': 91.914, '2005': 107.047, '2006': 123.084, '2007': 142.483, '2008': 180.384, '2009': 150.317, '2010': 177.785, '2011': 218.332, '2012': 227.144, '2013': 229.701, '2014': 238.943, '2015': 187.494, '2016': 180.764, '2017': 190.004, '2018': 194.507, '2019': 193.361, '2020': 164.774, '2021': 185.85, '2022': 225.652, '2023': 248.087, '2024': 269.14, '2025': 288.013, '2026': 284.984, '2027': 291.065, '2028': 297.245, '2029': 303.879, '2030': 308.997}, 'AND': {'2000': 1.429, '2001': 1.547, '2002': 1.758, '2003': 2.362, '2004': 2.896, '2005': 3.158, '2006': 3.456, '2007': 3.952, '2008': 4.082, '2009': 3.675, '2010': 3.446, '2011': 3.625, '2012': 3.189, '2013': 3.193, '2014': 3.267, '2015': 2.789, '2016': 2.895, '2017': 2.993, '2018': 3.217, '2019': 3.155, '2020': 2.885, '2021': 3.325, '2022': 3.376, '2023': 3.786, '2024': 4.038, '2025': 4.408, '2026': 4.715, '2027': 4.855, '2028': 5.001, '2029': 5.157, '2030': 5.318}, 'AGO': {'1980': 8.73, '1981': 8.17, '1982': 8.17, '1983': 8.514, '1984': 9.025, '1985': 11.119, '1986': 10.411, '1987': 11.9, '1988': 12.909, '1989': 15.017, '1990': 16.529, '1991': 16.022, '1992': 12.354, '1993': 8.966, '1994': 6.529, '1995': 8.148, '1996': 10.51, '1997': 12.344, '1998': 10.464, '1999': 9.895, '2000': 12.646, '2001': 12.378, '2002': 17.312, '2003': 20.342, '2004': 26.998, '2005': 41.397, '2006': 58.654, '2007': 73.038, '2008': 98.79, '2009': 81.705, '2010': 95.547, '2011': 125.552, '2012': 143.573, '2013': 153.761, '2014': 164.448, '2015': 131.661, '2016': 114.764, '2017': 139.835, '2018': 114.189, '2019': 94.671, '2020': 66.521, '2021': 84.375, '2022': 142.442, '2023': 112.483, '2024': 115.214, '2025': 115.167, '2026': 109.855, '2027': 114.798, '2028': 122.168, '2029': 130.394, '2030': 139.542}, 'ATG': {'1980': 0.132, '1981': 0.149, '1982': 0.166, '1983': 0.185, '1984': 0.212, '1985': 0.246, '1986': 0.298, '1987': 0.347, '1988': 0.411, '1989': 0.455, '1990': 0.479, '1991': 0.504, '1992': 0.525, '1993': 0.566, '1994': 0.625, '1995': 0.616, '1996': 0.679, '1997': 0.734, '1998': 0.79, '1999': 0.836, '2000': 0.901, '2001': 0.878, '2002': 0.898, '2003': 0.948, '2004': 1.026, '2005': 1.144, '2006': 1.304, '2007': 1.487, '2008': 1.558, '2009': 1.387, '2010': 1.298, '2011': 1.287, '2012': 1.365, '2013': 1.325, '2014': 1.379, '2015': 1.437, '2016': 1.49, '2017': 1.535, '2018': 1.662, '2019': 1.726, '2020': 1.412, '2021': 1.602, '2022': 1.867, '2023': 2.006, '2024': 2.208, '2025': 2.34, '2026': 2.456, '2027': 2.567, '2028': 2.683, '2029': 2.803, '2030': 2.929}, 'ARG': {'1980': 233.696, '1981': 189.802, '1982': 94.25, '1983': 116.267, '1984': 130.544, '1985': 98.599, '1986': 118.565, '1987': 121.561, '1988': 142.386, '1989': 91.352, '1990': 158.024, '1991': 211.979, '1992': 255.787, '1993': 264.429, '1994': 287.835, '1995': 288.497, '1996': 304.282, '1997': 327.436, '1998': 334.244, '1999': 316.998, '2000': 317.759, '2001': 300.421, '2002': 112.458, '2003': 142.431, '2004': 164.911, '2005': 199.273, '2006': 232.892, '2007': 287.921, '2008': 363.545, '2009': 334.633, '2010': 424.729, '2011': 527.644, '2012': 579.666, '2013': 611.471, '2014': 563.614, '2015': 642.464, '2016': 556.774, '2017': 643.861, '2018': 524.431, '2019': 446.762, '2020': 385.218, '2021': 486.04, '2022': 633.52, '2023': 648.895, '2024': 637.234, '2025': 683.371, '2026': 667.922, '2027': 710.438, '2028': 754.27, '2029': 798.651, '2030': 842.591}, 'ARM': {'1992': 0.108, '1993': 0.835, '1994': 0.648, '1995': 1.287, '1996': 1.597, '1997': 1.639, '1998': 1.892, '1999': 1.845, '2000': 1.912, '2001': 2.118, '2002': 2.376, '2003': 2.807, '2004': 3.577, '2005': 4.9, '2006': 6.384, '2007': 9.206, '2008': 11.662, '2009': 8.648, '2010': 9.26, '2011': 10.142, '2012': 10.619, '2013': 11.121, '2014': 11.61, '2015': 10.553, '2016': 10.546, '2017': 11.527, '2018': 12.458, '2019': 13.619, '2020': 12.642, '2021': 13.879, '2022': 19.514, '2023': 24.186, '2024': 25.955, '2025': 27.859, '2026': 29.082, '2027': 31.454, '2028': 33.676, '2029': 35.934, '2030': 38.388}, 'ABW': {'1995': 1.321, '1996': 1.38, '1997': 1.532, '1998': 1.665, '1999': 1.723, '2000': 1.873, '2001': 1.896, '2002': 1.962, '2003': 2.044, '2004': 2.255, '2005': 2.36, '2006': 2.47, '2007': 2.678, '2008': 2.843, '2009': 2.554, '2010': 2.454, '2011': 2.638, '2012': 2.615, '2013': 2.728, '2014': 2.791, '2015': 2.963, '2016': 2.984, '2017': 3.092, '2018': 3.276, '2019': 3.347, '2020': 2.456, '2021': 2.855, '2022': 3.266, '2023': 3.769, '2024': 4.192, '2025': 4.319, '2026': 4.471, '2027': 4.658, '2028': 4.83, '2029': 5.012, '2030': 5.193}, 'AUS': {'1980': 162.925, '1981': 188.411, '1982': 187.05, '1983': 179.479, '1984': 197.137, '1985': 174.386, '1986': 181.478, '1987': 213.101, '1988': 271.09, '1989': 308.402, '1990': 324.128, '1991': 324.437, '1992': 318.005, '1993': 309.304, '1994': 353.373, '1995': 379.227, '1996': 424.664, '1997': 426.402, '1998': 381.499, '1999': 411.968, '2000': 400.279, '2001': 378.114, '2002': 425.516, '2003': 541.156, '2004': 658.743, '2005': 736.505, '2006': 783.446, '2007': 950.093, '2008': 1056.565, '2009': 1000.831, '2010': 1254.622, '2011': 1515.504, '2012': 1570.139, '2013': 1519.895, '2014': 1456.939, '2015': 1233.914, '2016': 1262.645, '2017': 1381.106, '2018': 1417.158, '2019': 1386.289, '2020': 1362.665, '2021': 1655.838, '2022': 1725.433, '2023': 1742.311, '2024': 1795.492, '2025': 1829.508, '2026': 1948.227, '2027': 2036.053, '2028': 2132.013, '2029': 2228.386, '2030': 2335.258}, 'AUT': {'1980': 80.481, '1981': 69.738, '1982': 69.727, '1983': 70.644, '1984': 66.64, '1985': 68.248, '1986': 96.842, '1987': 121.104, '1988': 132.86, '1989': 132.534, '1990': 165.953, '1991': 173.481, '1992': 194.436, '1993': 189.342, '1994': 202.854, '1995': 239.914, '1996': 236.044, '1997': 211.978, '1998': 217.363, '1999': 216.637, '2000': 196.268, '2001': 196.479, '2002': 212.687, '2003': 260.714, '2004': 299.075, '2005': 314.126, '2006': 333.924, '2007': 386.806, '2008': 429.187, '2009': 398.857, '2010': 390.146, '2011': 428.879, '2012': 407.008, '2013': 426.587, '2014': 438.669, '2015': 379.584, '2016': 393.579, '2017': 414.78, '2018': 452.787, '2019': 443.033, '2020': 434.05, '2021': 480.786, '2022': 472.145, '2023': 511.833, '2024': 523.956, '2025': 566.456, '2026': 604.198, '2027': 625.678, '2028': 646.073, '2029': 666.33, '2030': 685.248}, 'AZE': {'1992': 1.193, '1993': 1.309, '1994': 2.258, '1995': 2.417, '1996': 3.177, '1997': 4.317, '1998': 4.28, '1999': 4.581, '2000': 5.273, '2001': 5.475, '2002': 6.232, '2003': 7.276, '2004': 8.682, '2005': 13.239, '2006': 20.983, '2007': 33.05, '2008': 48.852, '2009': 44.297, '2010': 52.909, '2011': 65.952, '2012': 69.684, '2013': 74.164, '2014': 75.235, '2015': 52.997, '2016': 37.83, '2017': 41.375, '2018': 47.113, '2019': 48.174, '2020': 42.693, '2021': 54.825, '2022': 78.807, '2023': 72.428, '2024': 74.316, '2025': 76.39, '2026': 80.024, '2027': 84.547, '2028': 89.615, '2029': 95.052, '2030': 100.823}, 'BHR': {'1980': 3.745, '1981': 4.228, '1982': 4.445, '1983': 4.554, '1984': 4.727, '1985': 4.46, '1986': 3.49, '1987': 3.78, '1988': 4.672, '1989': 4.873, '1990': 5.176, '1991': 5.43, '1992': 5.673, '1993': 6.241, '1994': 6.683, '1995': 7.075, '1996': 7.357, '1997': 7.629, '1998': 7.293, '1999': 7.905, '2000': 9.448, '2001': 9.579, '2002': 10.001, '2003': 11.546, '2004': 13.709, '2005': 16.647, '2006': 19.291, '2007': 22.653, '2008': 26.803, '2009': 23.913, '2010': 26.806, '2011': 29.915, '2012': 31.963, '2013': 33.823, '2014': 34.773, '2015': 32.523, '2016': 33.885, '2017': 37.205, '2018': 39.568, '2019': 40.447, '2020': 35.838, '2021': 40.84, '2022': 46.458, '2023': 46.192, '2024': 47.11, '2025': 47.391, '2026': 49.194, '2027': 51.339, '2028': 53.799, '2029': 56.505, '2030': 59.377}, 'BGD': {'1980': 24.775, '1981': 26.355, '1982': 24.678, '1983': 23.904, '1984': 26.817, '1985': 28.819, '1986': 29.639, '1987': 32.449, '1988': 34.914, '1989': 38.07, '1990': 41.068, '1991': 42.488, '1992': 43.292, '1993': 43.684, '1994': 46.438, '1995': 51.842, '1996': 55.445, '1997': 57.599, '1998': 59.879, '1999': 61.526, '2000': 61.687, '2001': 62.537, '2002': 65.036, '2003': 71.755, '2004': 77.152, '2005': 79.53, '2006': 86.028, '2007': 95.374, '2008': 109.765, '2009': 122.76, '2010': 138.094, '2011': 154.097, '2012': 159.749, '2013': 179.676, '2014': 207.102, '2015': 233.687, '2016': 265.236, '2017': 293.755, '2018': 321.379, '2019': 351.238, '2020': 373.902, '2021': 416.265, '2022': 460.201, '2023': 451.534, '2024': 450.461, '2025': 475.011, '2026': 519.288, '2027': 550.283, '2028': 596.228, '2029': 652.936, '2030': 716.74}, 'BRB': {'1980': 1.048, '1981': 1.154, '1982': 1.205, '1983': 1.28, '1984': 1.395, '1985': 1.46, '1986': 1.603, '1987': 1.765, '1988': 1.877, '1989': 2.077, '1990': 2.084, '1991': 2.092, '1992': 2.015, '1993': 2.136, '1994': 2.227, '1995': 2.348, '1996': 2.515, '1997': 2.667, '1998': 3.057, '1999': 3.21, '2000': 3.312, '2001': 3.306, '2002': 3.364, '2003': 3.479, '2004': 3.754, '2005': 4.213, '2006': 4.702, '2007': 5.273, '2008': 5.401, '2009': 5.064, '2010': 5.138, '2011': 5.302, '2012': 5.233, '2013': 5.338, '2014': 5.366, '2015': 5.288, '2016': 5.331, '2017': 5.517, '2018': 5.63, '2019': 5.788, '2020': 5.168, '2021': 5.275, '2022': 6.257, '2023': 6.721, '2024': 7.169, '2025': 7.559, '2026': 7.944, '2027': 8.344, '2028': 8.758, '2029': 9.195, '2030': 9.656}, 'BLR': {'1992': 12.8, '1993': 11.408, '1994': 15.687, '1995': 10.532, '1996': 14.494, '1997': 14.091, '1998': 15.215, '1999': 12.133, '2000': 10.785, '2001': 12.778, '2002': 15.092, '2003': 18.42, '2004': 23.928, '2005': 31.239, '2006': 38.219, '2007': 46.815, '2008': 62.798, '2009': 50.855, '2010': 57.22, '2011': 61.368, '2012': 65.669, '2013': 75.496, '2014': 78.736, '2015': 56.329, '2016': 47.703, '2017': 54.723, '2018': 60.011, '2019': 64.414, '2020': 61.312, '2021': 68.207, '2022': 73.735, '2023': 71.792, '2024': 76.208, '2025': 85.739, '2026': 90.556, '2027': 94.681, '2028': 99.486, '2029': 103.864, '2030': 108.074}, 'BEL': {'1980': 123.479, '1981': 102.245, '1982': 89.959, '1983': 85.037, '1984': 81.237, '1985': 84.468, '1986': 117.063, '1987': 145.412, '1988': 158.098, '1989': 159.817, '1990': 200.15, '1991': 205.37, '1992': 228.733, '1993': 218.721, '1994': 238.623, '1995': 288.302, '1996': 279.292, '1997': 253.022, '1998': 258.876, '1999': 258.503, '2000': 236.897, '2001': 236.748, '2002': 258.2, '2003': 318.004, '2004': 369.047, '2005': 385.927, '2006': 408.281, '2007': 470.978, '2008': 517.271, '2009': 484.488, '2010': 481.949, '2011': 527.106, '2012': 498.731, '2013': 524.106, '2014': 538.127, '2015': 461.091, '2016': 474.141, '2017': 500.733, '2018': 542.885, '2019': 536.787, '2020': 529.269, '2021': 598.92, '2022': 594.081, '2023': 644.84, '2024': 664.365, '2025': 716.98, '2026': 761.174, '2027': 780.384, '2028': 802.019, '2029': 824.347, '2030': 849.306}, 'BLZ': {'1980': 0.229, '1981': 0.238, '1982': 0.238, '1983': 0.251, '1984': 0.28, '1985': 0.278, '1986': 0.302, '1987': 0.354, '1988': 0.418, '1989': 0.482, '1990': 0.547, '1991': 0.597, '1992': 0.696, '1993': 0.752, '1994': 0.772, '1995': 0.819, '1996': 0.85, '1997': 0.873, '1998': 0.929, '1999': 1, '2000': 1.138, '2001': 1.172, '2002': 1.244, '2003': 1.308, '2004': 1.4, '2005': 1.474, '2006': 1.59, '2007': 1.706, '2008': 1.738, '2009': 1.688, '2010': 1.749, '2011': 1.832, '2012': 1.917, '2013': 2.035, '2014': 2.138, '2015': 2.193, '2016': 2.24, '2017': 2.266, '2018': 2.286, '2019': 2.381, '2020': 2.047, '2021': 2.429, '2022': 2.847, '2023': 3.052, '2024': 3.204, '2025': 3.297, '2026': 3.442, '2027': 3.561, '2028': 3.681, '2029': 3.802, '2030': 3.926}, 'BEN': {'1980': 2.302, '1981': 1.557, '1982': 1.542, '1983': 1.365, '1984': 1.456, '1985': 1.58, '1986': 2.036, '1987': 2.43, '1988': 2.552, '1989': 2.37, '1990': 2.89, '1991': 2.954, '1992': 3.284, '1993': 3.199, '1994': 2.227, '1995': 2.993, '1996': 3.251, '1997': 3.124, '1998': 3.362, '1999': 3.681, '2000': 3.522, '2001': 3.666, '2002': 4.191, '2003': 5.348, '2004': 6.187, '2005': 6.571, '2006': 7.034, '2007': 8.17, '2008': 9.787, '2009': 9.728, '2010': 9.543, '2011': 10.691, '2012': 11.148, '2013': 12.518, '2014': 13.288, '2015': 11.389, '2016': 11.818, '2017': 12.766, '2018': 14.346, '2019': 14.697, '2020': 15.674, '2021': 17.699, '2022': 17.439, '2023': 19.679, '2024': 21.487, '2025': 24.402, '2026': 27.453, '2027': 29.78, '2028': 32.298, '2029': 34.897, '2030': 37.733}, 'BTN': {'1980': 0.132, '1981': 0.143, '1982': 0.15, '1983': 0.162, '1984': 0.168, '1985': 0.174, '1986': 0.197, '1987': 0.238, '1988': 0.273, '1989': 0.272, '1990': 0.293, '1991': 0.254, '1992': 0.248, '1993': 0.26, '1994': 0.263, '1995': 0.308, '1996': 0.324, '1997': 0.362, '1998': 0.398, '1999': 0.418, '2000': 0.454, '2001': 0.474, '2002': 0.517, '2003': 0.616, '2004': 0.7, '2005': 0.818, '2006': 0.876, '2007': 1.071, '2008': 1.359, '2009': 1.273, '2010': 1.529, '2011': 1.88, '2012': 1.966, '2013': 1.995, '2014': 1.962, '2015': 2.159, '2016': 2.252, '2017': 2.462, '2018': 2.651, '2019': 2.618, '2020': 2.586, '2021': 2.621, '2022': 2.866, '2023': 2.923, '2024': 3.098, '2025': 3.408, '2026': 3.771, '2027': 4.109, '2028': 4.484, '2029': 4.961, '2030': 5.463}, 'BOL': {'1980': 3.589, '1981': 3.44, '1982': 3.813, '1983': 3.609, '1984': 3.752, '1985': 4.059, '1986': 3.97, '1987': 4.323, '1988': 4.598, '1989': 4.716, '1990': 4.868, '1991': 5.335, '1992': 5.635, '1993': 5.724, '1994': 5.974, '1995': 6.707, '1996': 7.385, '1997': 7.919, '1998': 8.49, '1999': 8.269, '2000': 8.385, '2001': 8.155, '2002': 7.917, '2003': 8.092, '2004': 8.785, '2005': 9.573, '2006': 11.52, '2007': 13.216, '2008': 16.792, '2009': 17.464, '2010': 19.786, '2011': 24.135, '2012': 27.282, '2013': 30.883, '2014': 33.237, '2015': 33.241, '2016': 34.189, '2017': 37.782, '2018': 40.581, '2019': 41.193, '2020': 36.897, '2021': 40.701, '2022': 44.329, '2023': 45.464, '2024': 46.967, '2025': 57.086}, 'BIH': {'1996': 3.584, '1997': 4.578, '1998': 5.281, '1999': 5.766, '2000': 5.568, '2001': 5.801, '2002': 6.728, '2003': 8.499, '2004': 10.17, '2005': 11.233, '2006': 12.877, '2007': 15.801, '2008': 19.188, '2009': 17.666, '2010': 17.207, '2011': 18.665, '2012': 17.237, '2013': 18.184, '2014': 18.588, '2015': 16.413, '2016': 17.124, '2017': 18.363, '2018': 20.504, '2019': 20.485, '2020': 20.264, '2021': 23.688, '2022': 24.581, '2023': 27.606, '2024': 29.614, '2025': 33.237, '2026': 36.239, '2027': 38.082, '2028': 40.004, '2029': 42.005, '2030': 44.106}, 'BWA': {'1980': 1.174, '1981': 1.037, '1982': 1.094, '1983': 1.208, '1984': 1.2, '1985': 1.117, '1986': 1.515, '1987': 2.374, '1988': 3.082, '1989': 3.441, '1990': 3.799, '1991': 3.802, '1992': 3.928, '1993': 3.957, '1994': 4.258, '1995': 4.805, '1996': 4.926, '1997': 5.011, '1998': 4.808, '1999': 5.413, '2000': 5.682, '2001': 5.46, '2002': 5.395, '2003': 7.469, '2004': 8.819, '2005': 9.833, '2006': 9.919, '2007': 10.566, '2008': 10.731, '2009': 10.118, '2010': 12.637, '2011': 15.111, '2012': 13.907, '2013': 14.272, '2014': 15.47, '2015': 13.531, '2016': 15.083, '2017': 16.105, '2018': 17.032, '2019': 16.696, '2020': 14.93, '2021': 18.75, '2022': 20.321, '2023': 19.411, '2024': 19.356, '2025': 19.186, '2026': 20.708, '2027': 22.333, '2028': 24.136, '2029': 26.386, '2030': 28.775}, 'BRA': {'1980': 145.819, '1981': 167.583, '1982': 179.166, '1983': 143.652, '1984': 142.957, '1985': 226.938, '1986': 263.256, '1987': 286.539, '1988': 320.105, '1989': 439.434, '1990': 455.335, '1991': 399.249, '1992': 382.465, '1993': 429.184, '1994': 546.764, '1995': 770.86, '1996': 851.146, '1997': 883.862, '1998': 864.307, '1999': 599.642, '2000': 655.454, '2001': 559.982, '2002': 509.798, '2003': 558.232, '2004': 669.29, '2005': 891.633, '2006': 1107.628, '2007': 1397.114, '2008': 1695.855, '2009': 1669.204, '2010': 2208.704, '2011': 2614.027, '2012': 2464.053, '2013': 2471.718, '2014': 2456.055, '2015': 1800.046, '2016': 1796.622, '2017': 2063.519, '2018': 1916.934, '2019': 1873.286, '2020': 1476.092, '2021': 1670.65, '2022': 1951.849, '2023': 2191.137, '2024': 2179.413, '2025': 2256.91, '2026': 2292.69, '2027': 2413.082, '2028': 2535.726, '2029': 2670.791, '2030': 2814.461}, 'BRN': {'1985': 4.831, '1986': 3.291, '1987': 3.872, '1988': 3.689, '1989': 4.109, '1990': 4.923, '1991': 5.254, '1992': 5.526, '1993': 5.588, '1994': 6.002, '1995': 7.153, '1996': 7.204, '1997': 7.043, '1998': 5.353, '1999': 5.779, '2000': 6.65, '2001': 6.206, '2002': 6.475, '2003': 7.266, '2004': 8.723, '2005': 10.561, '2006': 12.71, '2007': 13.571, '2008': 15.949, '2009': 11.892, '2010': 13.707, '2011': 18.525, '2012': 19.048, '2013': 18.094, '2014': 17.098, '2015': 12.93, '2016': 11.4, '2017': 12.128, '2018': 13.567, '2019': 13.469, '2020': 12.006, '2021': 14.006, '2022': 16.682, '2023': 15.095, '2024': 15.463, '2025': 15.565, '2026': 16.457, '2027': 17.575, '2028': 18.477, '2029': 19.506, '2030': 20.442}, 'BGR': {'1980': 37.751, '1981': 40.718, '1982': 42.467, '1983': 43.641, '1984': 46.358, '1985': 39.692, '1986': 35.13, '1987': 40.721, '1988': 66.546, '1989': 67.774, '1990': 29.882, '1991': 2.928, '1992': 11.882, '1993': 6.449, '1994': 11.338, '1995': 18.992, '1996': 12.295, '1997': 11.317, '1998': 15.031, '1999': 13.628, '2000': 13.246, '2001': 14.183, '2002': 16.403, '2003': 21.146, '2004': 26.158, '2005': 29.868, '2006': 34.38, '2007': 44.432, '2008': 54.476, '2009': 52.024, '2010': 50.69, '2011': 57.682, '2012': 54.297, '2013': 55.82, '2014': 57.081, '2015': 50.766, '2016': 53.929, '2017': 59.288, '2018': 66.318, '2019': 68.639, '2020': 70.658, '2021': 84.477, '2022': 90.719, '2023': 102.434, '2024': 112.232, '2025': 127.924, '2026': 142.203, '2027': 151.081, '2028': 159.77

In [78]:
#################################
# Convert the All-GDP JSON into a data frame
#################################

all_gdp_data = df2_response_json['values']['NGDPD']
df_all_gdp_data = pd.DataFrame(all_gdp_data)
df_all_gdp_data.head()

,SDN,AFG,ALB,DZA,AND,AGO,ATG,ARG,ARM,ABW,...,NMQ,OAE,PIQ,SMQ,SAQ,SEQ,SSA,WEQ,WHQ,WEOWORLD
1980,9.095,NaN,1.946,45.957,NaN,8.730,0.132,233.696,NaN,NaN,...,3389.979,776.001,5.925,581.096,257.208,245.909,322.168,3841.214,4024.549,11257.209
1981,6.530,NaN,2.229,48.156,NaN,8.170,0.149,189.802,NaN,NaN,...,3841.238,791.714,5.890,583.981,273.450,248.004,340.015,3431.522,4480.424,11552.049
1982,4.748,NaN,2.296,48.599,NaN,8.170,0.166,94.250,NaN,NaN,...,3900.909,786.892,5.639,494.458,283.385,263.685,342.696,3302.950,4453.207,11340.968
1983,6.485,NaN,2.319,51.582,NaN,8.514,0.185,116.267,NaN,NaN,...,4177.174,785.593,5.535,463.468,298.216,270.473,317.323,3211.548,4700.197,11650.964
1984,7.992,NaN,2.290,55.906,NaN,9.025,0.212,130.544,NaN,NaN,...,4630.542,823.796,5.337,454.181,300.023,307.009,252.021,3085.770,5151.479,12065.980

In [79]:
################################
# Filter the new data frame to just 2025 for every country
################################

df_gdp_2025 = df_all_gdp_data[df_all_gdp_data.index == '2025']
df_gdp_2025.head()

,SDN,AFG,ALB,DZA,AND,AGO,ATG,ARG,ARM,ABW,...,NMQ,OAE,PIQ,SMQ,SAQ,SEQ,SSA,WEQ,WHQ,WEOWORLD
2025,35.897,NaN,29.939,288.013,4.408,115.167,2.34,683.371,27.859,4.319,...,34888.628,9707.013,44.229,4446.822,5166.959,4169.457,2081.399,23880.966,40026.574,117165.394

In [87]:
##################################
# Reformat as a long column for a table view
##################################

# Transpose the df_gdp_2025 DataFrame
df_gdp_2025_transposed = df_gdp_2025.T

# Rename the column containing the GDP values to '2025 GDP'
df_gdp_2025_transposed.rename(columns={'2025': '2025 GDP'}, inplace=True)

# Reset the index and rename the new column to 'Country'
df_gdp_2025_transposed.reset_index(inplace=True)
df_gdp_2025_transposed.rename(columns={'index': 'Country Code'}, inplace=True)

df_gdp_2025_transposed.head(200)

    Country Code   2025 GDP
0            SDN     35.897
1            AFG        NaN
2            ALB     29.939
3            DZA    288.013
4            AND      4.408
..           ...        ...
195          ZMB     29.369
196          ZWE     53.310
197        ADVEC  68598.619
198          AFQ   3057.762
199          SSQ   2133.863

[200 rows x 2 columns]

In [81]:
#######################
# Replacing country codes with country names
#######################

## This API includes a dictionary of full country names for each code. Task is to take this and combine it with the existing table, replacing the codes.

countries = requests.get("https://www.imf.org/external/datamapper/api/v1/countries")
df_countries = pd.DataFrame(countries.json())

# Making codes a column instead of the index
df_countries.reset_index(inplace=True)
df_countries.rename(columns={'index': 'Country Code'}, inplace=True)

# Extract the country name from the dictionary in the 'countries' column
df_countries['countries'] = df_countries['countries'].apply(lambda x: x.get('label') if isinstance(x, dict) else x)

df_countries.head()

  Country Code    countries  api
0          ABW        Aruba  NaN
1          AFG  Afghanistan  NaN
2          AGO       Angola  NaN
3          AIA     Anguilla  NaN
4          ALB      Albania  NaN

In [82]:
######################
# Merging the country codes with GDP and country codes with full country names to get full country names and GDP in same data frame
######################

# Merging to create list of country with readable names instead of codes

pd.merge(df_gdp_2025_transposed, df_countries, on="Country Code", how="outer")

      Country Code   2025 GDP     countries   api
0              ABW      4.319         Aruba   NaN
1            ADVEC  68598.619           NaN   NaN
2              AFG        NaN   Afghanistan   NaN
3              AFQ   3057.762           NaN   NaN
4              AGO    115.167        Angola   NaN
..             ...        ...           ...   ...
270            ZAF    426.383  South Africa   NaN
271            ZMB     29.369        Zambia   NaN
272            ZWE     53.310      Zimbabwe   NaN
273  output-method        NaN           NaN  json
274        version        NaN           NaN     1

[275 rows x 4 columns]

In [83]:
#################################
# Pulling IMF codes for regions which for some reason are in a different API endpoint
#################################

response_regions = requests.get("https://www.imf.org/external/datamapper/api/v1/regions")
df_regions = pd.DataFrame(response_regions.json())

# Making codes a column instead of the index
df_regions.reset_index(inplace=True)
df_regions.rename(columns={'index': 'Country Code', 'regions': 'countries'}, inplace=True)

# Extract the country name from the dictionary in the 'regions' column
df_regions['countries'] = df_regions['countries'].apply(lambda x: x.get('label') if isinstance(x, dict) else x)

df_regions.head(30)

     Country Code                          countries   api
0             AFQ                    Africa (Region)   NaN
1          AFRREO  African Regional Economic Outlook   NaN
2             APQ                   Asia and Pacific   NaN
3             AZQ          Australia and New Zealand   NaN
4             CAQ      Central Asia and the Caucasus   NaN
5             CBQ                          Caribbean   NaN
6             CMQ                    Central America   NaN
7             EAQ                          East Asia   NaN
8             EEQ                    Eastern Europe    NaN
9             EUQ                             Europe   NaN
10            MEQ               Middle East (Region)   NaN
11            NAQ                       North Africa   NaN
12            NMQ                      North America   NaN
13            PIQ                   Pacific Islands    NaN
14            SAQ                         South Asia   NaN
15            SEQ                     Southeast Asia   NaN
16            SMQ                      South America   NaN
17            SSQ       Sub-Saharan Africa (Region)    NaN
18            WEQ                     Western Europe   NaN
19            WHQ        Western Hemisphere (Region)   NaN
20        AFR_SSQ       Sub-Saharan Africa (Region)    NaN
21    SPR_GD_MECA       Middle East and Central Asia   NaN
22     SPR_GD_EUR                             Europe   NaN
23     SPR_GD_AFR                             Africa   NaN
24     SPR_GD_CPI      Caribbean and Pacific Islands   NaN
25     SPR_GD_WHD                 Western Hemisphere   NaN
26    SPR_GD_Asia                               Asia   NaN
27        version                                NaN     1
28  output-method                                NaN  json

In [84]:
#######################
# Ranking from highest to lowest by country GDP
#######################

df_GDP = pd.merge(df_gdp_2025_transposed, df_countries, on="Country Code", how="outer")
df_GDP_all = pd.merge(df_GDP, df_regions, on="Country Code", how="outer")

# Display every value for quick visibiilty
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# Sort highest to lowest and display
ranked_gdp = df_GDP_all.sort_values("2025 GDP", ascending=False)

print(ranked_gdp)

pd.reset_option('display.max_rows')
pd.reset_option('display.max_columns')

      Country Code    2025 GDP                       countries_x api_x  \
272       WEOWORLD  117165.394                               NaN   NaN
1            ADVEC   68598.619                               NaN   NaN
147            MAE   52056.759                               NaN   NaN
187          OEMDC   48566.775                               NaN   NaN
10             APQ   40601.732                               NaN   NaN
274            WHQ   40026.574                               NaN   NaN
181            NMQ   34888.628                               NaN   NaN
260            USA   30615.743                     United States   NaN
83             EUQ   29676.875                               NaN   NaN
65              DA   27821.017                               NaN   NaN
72             EAQ   26874.702                               NaN   NaN
273            WEQ   23880.966                               NaN   NaN
82              EU   21096.780                               NaN   NaN
49             CHN   19398.577       China, People's Republic of   NaN
84            EURO   17748.965                               NaN   NaN
186            OAE    9707.013                               NaN   NaN
271             WE    7000.686                               NaN   NaN
74             EDE    6463.042                               NaN   NaN
75             EEQ    5795.909                               NaN   NaN
153           MECA    5200.632                               NaN   NaN
208            SAQ    5166.959                               NaN   NaN
66             DEU    5013.574                           Germany   NaN
219            SMQ    4446.822                               NaN   NaN
125            JPN    4279.828                             Japan   NaN
212            SEQ    4169.457                               NaN   NaN
115            IND    4125.213                             India   NaN
92             GBR    3958.780                    United Kingdom   NaN
154            MEQ    3723.087                               NaN   NaN
14             AS5    3540.744                               NaN   NaN
88             FRA    3361.557                            France   NaN
3              AFQ    3057.762                               NaN   NaN
122            ITA    2543.677                             Italy   NaN
206            RUS    2540.656                Russian Federation   NaN
43             CAN    2283.599                            Canada   NaN
37             BRA    2256.910                            Brazil   NaN
44             CAQ    2253.966                               NaN   NaN
232            SSQ    2133.863                               NaN   NaN
22             AZQ    2092.418                               NaN   NaN
230            SSA    2081.399                               NaN   NaN
79             ESP    1891.371                             Spain   NaN
155            MEX    1862.740                            Mexico   NaN
132            KOR    1858.572                Korea, Republic of   NaN
19             AUS    1829.508                         Australia   NaN
253            TUR    1565.471              Türkiye, Republic of   NaN
113            IDN    1443.256                         Indonesia   NaN
180            NLD    1320.635                       Netherlands   NaN
209            SAU    1268.535                      Saudi Arabia   NaN
197            POL    1039.619                            Poland   NaN
46             CHE    1002.666                       Switzerland   NaN
174            NAQ     923.899                               NaN   NaN
255            TWN     884.387          Taiwan Province of China   NaN
24             BEL     716.980                           Belgium   NaN
117            IRL     708.771                           Ireland   NaN
12             ARG     683.371                         Argentina   NaN
237            SWE     662.318                            Sweden   NaN
121            ISR     610.752                            Israel   NaN
213            SGP     574.185                         Singapore   NaN
11             ARE     569.097              United Arab Emirates   NaN
20             AUT     566.456                           Austria   NaN
245            THA     558.573                          Thailand   NaN
51             CMQ     540.363                               NaN   NaN
182            NOR     517.102                            Norway   NaN
193            PHL     494.158                       Philippines   NaN
268            VNM     484.726                           Vietnam   NaN
28             BGD     475.011                        Bangladesh   NaN
171            MYS     470.572                          Malaysia   NaN
69             DNK     459.612                           Denmark   NaN
56             COL     438.121                          Colombia   NaN
108            HKG     428.233                     Hong Kong SAR   NaN
278            ZAF     426.383                      South Africa   NaN
205            ROU     422.508                           Romania   NaN
189            PAK     410.495                          Pakistan   NaN
64             CZE     383.384                    Czech Republic   NaN
118            IRN     356.513                              Iran   NaN
76             EGY     349.264                             Egypt   NaN
48             CHL     347.174                             Chile   NaN
200            PRT     337.936                          Portugal   NaN
192            PER     318.480                              Peru   NaN
85             FIN     314.724                           Finland   NaN
126            KAZ     300.052                        Kazakhstan   NaN
71             DZA     288.013                           Algeria   NaN
177            NGA     285.003                           Nigeria   NaN
101            GRC     282.019                            Greece   NaN
119            IRQ     265.455                              Iraq   NaN
185            NZL     262.909                       New Zealand   NaN
112            HUN     247.759                           Hungary   NaN
203            QAT     222.119                             Qatar   NaN
258            UKR     209.713                           Ukraine   NaN
148            MAR     179.612                           Morocco   NaN
134            KWT     157.469                            Kuwait   NaN
235            SVK     154.587                   Slovak Republic   NaN
45             CBQ     150.761                               NaN   NaN
262            UZB     137.480                        Uzbekistan   NaN
127            KEN     136.014                             Kenya   NaN
73             ECU     130.529                           Ecuador   NaN
70             DOM     129.748                Dominican Republic   NaN
29             BGR     127.924                          Bulgaria   NaN
198            PRI     126.546                       Puerto Rico   NaN
104            GTM     120.850                         Guatemala   NaN
6              AGO     115.167                            Angola   NaN
94             GHA     111.963                             Ghana   NaN
81             ETH     109.492                          Ethiopia   NaN
188            OMN     105.190                              Oman   NaN
110            HRV     103.901                           Croatia   NaN
59             CRI     102.637                        Costa Rica   NaN
144            LUX     100.642                        Luxembourg   NaN
229            SRB     100.048                            Serbia   NaN
50             CIV      99.207                     Côte d'Ivoire   NaN
143            LTU      95.274                         Lithuania   NaN
190            PAN      90.408                            Panama   NaN
256            TZA      87.444                          Tanzania   NaN
33             BLR      85.739                           Belarus   NaN
259            URY      84.986                           Uruguay   NaN
265            VEN      82.767                         Venezuela   NaN
53             COD      82.262           Congo, Dem. Rep. of the   NaN
236            SVN      79.221                          Slovenia   NaN
21             AZE      76.390                        Azerbaijan   NaN
248            TKM      72.119                      Turkmenistan   NaN
257            UGA      64.993                            Uganda   NaN
52             CMR      60.577                          Cameroon   NaN
161            MMR      60.561                           Myanmar   NaN
252            TUN      59.069                           Tunisia   NaN
36             BOL      57.086                           Bolivia   NaN
124            JOR      56.157                            Jordan   NaN
280            ZWE      53.310                          Zimbabwe   NaN
146            MAC      52.379                         Macao SAR   NaN
129            KHM      48.802                          Cambodia   NaN
138            LBY      47.941                             Libya   NaN
145            LVA      47.880                            Latvia   NaN
201            PRY      47.398                          Paraguay   NaN
30             BHR      47.391                           Bahrain   NaN
80             EST      46.763                           Estonia   NaN
183            NPL      45.513                             Nepal   NaN
194            PIQ      44.229                               NaN   NaN
63             CYP      39.943                            Cyprus   NaN
109            HND      39.445                          Honduras   NaN
120            ISL      38.386                           Iceland   NaN
93             GEO      37.403                           Georgia   NaN
211            SEN      36.839                           Senegal   NaN
218            SLV      36.587                       El Salvador   NaN
210            SDN      35.897                             Sudan   NaN
32             BIH      33.237            Bosnia and Herzegovina   NaN
196            PNG      32.714                  Papua New Guinea   NaN
111            HTI      30.908                             Haiti   NaN
8              ALB      29.939                           Albania   NaN
279            ZMB      29.369                            Zambia   NaN
13             ARM      27.859                           Armenia   NaN
160            MLT      27.745                             Malta   NaN
96             GIN      27.515                            Guinea   NaN
27             BFA      26.866                      Burkina Faso   NaN
251            TTO      26.002               Trinidad and Tobago   NaN
159            MLI      25.591                              Mali   NaN
163            MNG      25.105                          Mongolia   NaN
107            GUY      25.064                            Guyana   NaN
165            MOZ      24.726                        Mozambique   NaN
25             BEN      24.402                             Benin   NaN
123            JAM      23.137                           Jamaica   NaN
176            NER      22.969                             Niger   NaN
243            TCD      21.592                              Chad   NaN
91             GAB      21.455                             Gabon   NaN
178            NIC      20.689                         Nicaragua   NaN
128            KGZ      20.160                   Kyrgyz Republic   NaN
150            MDA      19.620                           Moldova   NaN
151            MDG      19.377                        Madagascar   NaN
41             BWA      19.186                          Botswana   NaN
158            MKD      18.783                  North Macedonia    NaN
277            YEM      17.352                             Yemen   NaN
246            TJK      17.032                        Tajikistan   NaN
135            LAO      16.934                        Lao P.D.R.   NaN
31             BHS      16.393                      Bahamas, The   NaN
169            MUS      15.730                         Mauritius   NaN
54             COG      15.695               Congo, Republic of    NaN
39             BRN      15.565                 Brunei Darussalam   NaN
170            MWI      14.975                            Malawi   NaN
207            RWA      14.771                            Rwanda   NaN
173            NAM      14.686                           Namibia   NaN
100            GNQ      13.467                 Equatorial Guinea   NaN
221            SOM      12.944                           Somalia   NaN
261            UVK      12.672                            Kosovo   NaN
166            MRT      11.953                        Mauritania   NaN
244            TGO      10.951                              Togo   NaN
140            LIE       9.424                     Liechtenstein   NaN
162            MNE       9.353                        Montenegro   NaN
217            SLE       8.639                      Sierra Leone   NaN
152            MDV       7.676                          Maldives   NaN
38             BRB       7.559                          Barbados   NaN
23             BDI       7.025                           Burundi   NaN
86             FJI       6.336                              Fiji   NaN
238            SWZ       5.201                          Eswatini   NaN
137            LBR       5.182                           Liberia   NaN
231            SSD       4.979          South Sudan, Republic of   NaN
67             DJI       4.613                          Djibouti   NaN
234            SUR       4.496                          Suriname   NaN
9              AND       4.408                           Andorra   NaN
0              ABW       4.319                             Aruba   NaN
40             BTN       3.408                            Bhutan   NaN
42             CAF       3.300          Central African Republic   NaN
34             BLZ       3.297                            Belize   NaN
58             CPV       2.915                        Cabo Verde   NaN
139            LCA       2.659                       Saint Lucia   NaN
98             GMB       2.497                       Gambia, The   NaN
99             GNB       2.474                     Guinea-Bissau   NaN
142            LSO       2.390                           Lesotho   NaN
16             ATG       2.340               Antigua and Barbuda   NaN
220            SMR       2.241                        San Marino   NaN
240            SYC       2.230                        Seychelles   NaN
249            TLS       2.125                       Timor-Leste   NaN
216            SLB       1.904                   Solomon Islands   NaN
57             COM       1.613                           Comoros   NaN
102            GRD       1.458                           Grenada   NaN
276            WSM       1.248                             Samoa   NaN
264            VCT       1.238  Saint Vincent and the Grenadines   NaN
131            KNA       1.141             Saint Kitts and Nevis   NaN
269            VUT       1.119                           Vanuatu   NaN
233            STP       0.976             São Tomé and Príncipe   NaN
68             DMA       0.748                          Dominica   NaN
250            TON       0.587                             Tonga   NaN
90             FSM       0.495        Micronesia, Fed. States of   NaN
195            PLW       0.341                             Palau   NaN
130            KIR       0.321                          Kiribati   NaN
157            MHL       0.302                  Marshall Islands   NaN
184            NRU       0.172                             Nauru   NaN
254            TUV       0.058                            Tuvalu   NaN
2              AFG         NaN                       Afghanistan   NaN
4           AFRREO         NaN                               NaN   NaN
5          AFR_SSQ         NaN                               NaN   NaN
7              AIA         NaN                          Anguilla   NaN
15             ASM         NaN                    American Samoa   NaN
17             ATI         NaN                              None   NaN
18             ATL         NaN                              None   NaN
26             BES         NaN  Bonaire, Sint Eustatius and Saba   NaN
35             BMU         NaN                           Bermuda   NaN
47             CHI         NaN                   Channel Islands   NaN
55             COK         NaN                      Cook Islands   NaN
60             CUB         NaN                              Cuba   NaN
61             CUW         NaN                           Curacao   NaN
62             CYM         NaN                    Cayman Islands   NaN
77             ERI         NaN                           Eritrea   NaN
78             ESH         NaN                    Western Sahara   NaN
87             FLK         NaN                  Falkland Islands   NaN
89             FRO         NaN                    Faeroe Islands   NaN
95             GIB         NaN                         Gibraltar   NaN
97             GLP         NaN                        Guadeloupe   NaN
103            GRL         NaN                         Greenland   NaN
105            GUF         NaN                     French Guiana   NaN
106            GUM         NaN                              Guam   NaN
114            IMY         NaN                       Isle of Man   NaN
116            IOT         NaN  British Indian Ocean Territories   NaN
133            KOS         NaN                            Kosovo   NaN
136            LBN         NaN                           Lebanon   NaN
141            LKA         NaN                         Sri Lanka   NaN
149            MCO         NaN                            Monaco   NaN
156            MFX         NaN                      Saint Martin   NaN
164            MNP         NaN          Northern Mariana Islands   NaN
167            MSR         NaN                        Montserrat   NaN
168            MTQ         NaN                        Martinique   NaN
172            MYT         NaN                           Mayotte   NaN
175            NCL         NaN                     New Caledonia   NaN
179            NIU         NaN                              Niue   NaN
191            PCN         NaN                          Pitcairn   NaN
199            PRK         NaN      Korea, Dem. People's Rep. of   NaN
202            PYF         NaN                  French Polynesia   NaN
204            REU         NaN                           Reunion   NaN
214            SHN         NaN                      Saint Helena   NaN
215            SJM         NaN    Svalbard and Jan Mayen Islands   NaN
222            SPM         NaN         Saint-Pierre and Miquelon   NaN
223     SPR_GD_AFR         NaN                               NaN   NaN
224    SPR_GD_Asia         NaN                               NaN   NaN
225     SPR_GD_CPI         NaN                               NaN   NaN
226     SPR_GD_EUR         NaN                               NaN   NaN
227    SPR_GD_MECA         NaN                               NaN   NaN
228     SPR_GD_WHD         NaN                               NaN   NaN
239            SXM         NaN                      Sint Maarten   NaN
241            SYR         NaN                             Syria   NaN
242            TCA         NaN          Turks and Caicos Islands   NaN
247            TKL         NaN                           Tokelau   NaN
263            VAT         NaN                          Holy See   NaN
266            VGB         NaN            British Virgin Islands   NaN
267            VIR         NaN     United States Virgin Islands    NaN
270            WBG         NaN                West Bank and Gaza   NaN

In [85]:
# Drop the 'api' column
ranked_gdp_cleaned = ranked_gdp.drop(columns=['api'])

# Reset the index and drop the old one
ranked_gdp_cleaned = ranked_gdp_cleaned.reset_index(drop=True)

# Display the cleaned DataFrame
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
print(ranked_gdp_cleaned)
pd.reset_option('display.max_rows')
pd.reset_option('display.max_columns')

KeyError: "['api'] not found in axis"

In [ ]:
# Compare final to Vercel dashboard